/* Project Euler: Problem 2 - Even Fibonacci Numbers
   https://projecteuler.net/problem=2

   Each new term in the Fibonacci sequence is generated by adding the previous
   two terms.

   By starting with 1 and 2, the first 10 terms will be:

      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

   By considering the terms in the Fibonacci sequence whose values do not
   exceed four million, find the sum of the even-valued terms.
*/

function fibo(digit) {
  'use strict';
  if (!fibo.cache[digit]) {
    var result = {};
    result = (digit === 0) ? 0 :
             (digit === 1) ? 1 :
             fibo(digit - 1) + fibo(digit - 2);
    fibo.cache[digit] = result;
  }

  return fibo.cache[digit];
}

// Add 'cache' object as a property of the function
fibo.cache = {};

function evenFibSum(max) {
  'use strict';
  var i,
      sum = 0,
      fibVal = 0;
  // Every 3rd digit in the Fibonacci sequence is a multiple of 2
  for (i = 3;; i += 3) {
    fibVal = fibo(i);
    if (fibVal >= max) { break; }

    sum += fibVal;
  }

  return sum;
}

evenFibSum(4000000);
